name: Deploy

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: start deploy script via ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ./deploy/avito_scrapper.sh
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}